# Generated by Django 5.2.4 on 2025-08-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0002_add_attendance_models'),
        ('paie', '0002_userprofile_system'),
    ]

    operations = [
    ]
